spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:info
    type: com.alibaba.druid.pool.DruidDataSource

  #    freemarker静态资源配置
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    tempalte-loader-path: classpath:/templates/

#公共配置与profiles选择无关
mybatis:
  type-aliases-package: com.see.any.dao.pojo
  mapper-locations: classpath*:com/see/any/dao/mapper/*.xml
